FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --default-timeout=300 --no-cache-dir -r requirements.txt

COPY forecast_api.py .

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "forecast_api:app", "--host", "0.0.0.0", "--port", "8000"]
